### ISSUE TITLE
Zero safety controller tag prevents movement/self collision checks

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_setup_assistant#2]
The solidworks to URDF generator currently outputs safety_controller tags like the following:

<safety_controller
soft_lower_limit="0"
soft_upper_limit="0"
k_position="0"
k_velocity="0" />

https://kforge.ros.org/robotmodel/sw_urdf_exporter_trac/ticket/31

Even though the joints themselves have real upper and lower limits, MoveIT does not work for these URDFs.  For example, the Optimize Self-Collision Checking is broken.  It does not move joints, so no joints are ever possibly in collision.

Likely, if both of these safety limits are 0, this is a special default case, and MoveIT should ignore them.  This page seems to imply this reasoning:
http://www.ros.org/wiki/urdf/XML/joint

With safety_controller tag:
Statistics: 
     9 : Total Links
    36 : Total possible collisions
     0 : Always in collision
    28 : Never in collision
     0 : Default in collision
     8 : Adjacent links disabled
     0 : Sometimes in collision
    36 : TOTAL DISABLED
Copy to Spreadsheet:
9   36  0   28  0   8   0   36
[ INFO] [1351556483.651907539]: Thread complete 36

Expected output:
Statistics: 
     9 : Total Links
    36 : Total possible collisions
     0 : Always in collision
    19 : Never in collision
     0 : Default in collision
     8 : Adjacent links disabled
     9 : Sometimes in collision
    27 : TOTAL DISABLED
Copy to Spreadsheet:
9   36  0   19  0   8   9   27
[ INFO] [1351557308.526624000]: Thread complete 36

**Comment by isucan** [comment]
Hey Chad,

I see where the problem is. However, the fact that defaults are 0 does not mean that if the user sets it to 0 we should treat the value the same as if it were not specified. I am reluctant to add a check that ignores the joint limits for the case you mention. I think the right way is to fix the urdf for now, and the urdf exporter otherwise.

**Comment by chadrockey** [comment]
I agree that a single 0 value should not be ignored.  If you choose to implement this it should be only in the case that:

soft_lower_limit == soft_upper_limit == 0

The reference (http://www.ros.org/wiki/urdf/XML/joint) states that these two values are "(optional, defaults to 0)"  I do not have evidence of people "disabling" these limits by setting both to zero, but it would make sense that if the limits are the same, then the joint is fixed and not really a joint.

I don't think the urdf exporter should output these the way they are, but it is a major breakage for MoveIT.  If you choose not to ignore these values, you should at least spit out a console warning or fail the self-collisions check.  Otherwise, the process can complete with an arm that does not work in MoveIT but works through joint_state_publisher.

**Comment by isucan** [comment]
I see what you mean. I understand this breaks your use case, but I don't
think the right way to fix things is updating the way we process joint
limits in MoveIt. However, I will add a warning for the case of  a joint
becoming essentially fixed, due to the imposed limits. Until the URDF
exporter gets fixed, do you think you could edit the generated URDF
manually to remove the joint limits?
